[2025-03-01 12:25:55] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 12:36:41] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 13:24:50] Error: time data ' Expiry Date 2025-03-31 12:36:51' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' Expiry Date 2025-03-31 12:36:51' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 14:19:53] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 14:31:27] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 14:31:28] Received login request - IP: Unknown IP, MAC: Unknown MAC
[2025-03-01 15:27:29] Error: time data ' Expiry Date 2025-03-31 15:12:35' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' Expiry Date 2025-03-31 15:12:35' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 15:27:59] Received login request - IP: Unknown IP, MAC: Unknown MAC
Unknown MAC,Unknown IP,0112735877,2 HOURS,2025-03-31 15:28:14
[2025-03-01 15:30:23] Error: time data ' Expiry Date 2025-03-31 15:28:14' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' Expiry Date 2025-03-31 15:28:14' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 15:32:00] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 15:32:01] Received login request - IP: Unknown IP, MAC: Unknown MAC
[2025-03-01 16:27:29] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 18:51:33] Received login request - IP: Unknown IP, MAC: Unknown MAC
[2025-03-01 18:59:08] Error: time data ' Expiry Date 2025-03-31 18:58:38' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' Expiry Date 2025-03-31 18:58:38' does not match format '%Y-%m-%d %H:%M:%S'

AA:EE:B4:F7:C6:B8,192.168.89.209,0746120864,2 HOURS,2025-03-31 19:00:43
[2025-03-01 19:02:31] Error: time data ' Expiry Date 2025-03-31 19:00:43' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data ' Expiry Date 2025-03-31 19:00:43' does not match format '%Y-%m-%d %H:%M:%S'

[2025-03-01 19:39:48] Error: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'
Traceback (most recent call last):
  File "C:\Users\A\Desktop\new5\my_project\server.py", line 70, in remove_expired_users
    expiry_date = datetime.datetime.strptime(expiry_date, "%Y-%m-%d %H:%M:%S")
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '"Amount":5' does not match format '%Y-%m-%d %H:%M:%S'

